services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      DJANGO_SETTINGS_MODULE: wagtail_template.settings.dev
      DJANGO_ENV: development
    env_file: .env
    volumes:
      - .:/app
    init: true
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
